[package]
name = "todo-list"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.27", features = ["derive"] }
csv = "1.3.1"
fs2 = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
